version: "3.8"
services:
  scraper:
    build: .
    image: news-scraper
    container_name: scraper
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "1876:1876"
    environment:
      - CHROMEDRIVER_PATH=/usr/local/bin/chromedriver
